version: "3"
services:
    log:
        image: p2pviewer
        networks:
            - chord
    bootnode:
        image: chord
        networks:
            - chord
        ports:
            - 8090:8090/udp
        depends_on:
            - log
        command: bash -x /app/runbootnode.sh
    nodes:
        image: chord
        ports:
            - 8091:8091/udp
        networks:
            - chord
        deploy:
            replicas: 1
        depends_on:
            - log
            - bootnode
        command: bash  -x /app/runnodes.sh
networks:
    chord:

